[package]
name = "css-to-snippets"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
